#include <stdlib.h>
#include <stdio.h>
#include <string.h>

int main()
{

	int i = 0;
	int start = 0;
	int y = 0;
	int x = 0;
	char *map = ">><><><<>>><<><><<<<<>><><>>>><><<><<>>>><<<><<>><<<<<>><<<<<<<<<>><>>><>><>>><<<<>>>>><>>><<><<><><><>>>>>>><<><<<<<>>><<<>><<<>>><<<<<<<<<<<<<<<>>>><<><><>>>>>>>>><>><>>><>>>>>>>><<><<>>>>";
	char *map2 = "BAS_BAS_BAS_BAS_BAS_HAUT_BAS_BAS_GAUCHE_BAS_HAUT_BAS_BAS_BAS_BAS_BAS_HAUT_HAUT_GAUCHE_HAUT_GAUCHE_DROITE_BAS_DROITE_BAS_HAUT_HAUT_DROITE_DROITE_BAS_HAUT_BAS_DROITE_HAUT_DROITE_BAS_DROITE_BAS_BAS_BAS_GAUCHE_DROITE_BAS_BAS_DROITE_BAS_BAS_HAUT_BAS_GAUCHE_HAUT_BAS_HAUT_BAS_BAS_BAS_BAS_BAS_BAS_GAUCHE_GAUCHE_BAS_HAUT_HAUT_BAS_DROITE_BAS_GAUCHE_DROITE_BAS_GAUCHE_HAUT_BAS_DROITE_BAS_HAUT_GAUCHE_BAS_HAUT_HAUT_HAUT_BAS_DROITE_BAS_BAS_BAS_DROITE_GAUCHE_GAUCHE_BAS_GAUCHE_BAS_HAUT_DROITE_HAUT_BAS_BAS_GAUCHE_BAS_BAS_BAS_DROITE_BAS_GAUCHE_BAS_GAUCHE_GAUCHE_GAUCHE_BAS_BAS_GAUCHE_GAUCHE_BAS_GAUCHE_BAS_GAUCHE_GAUCHE_GAUCHE_DROITE_DROITE_BAS_GAUCHE_DROITE_GAUCHE_BAS_DROITE_GAUCHE_DROITE_GAUCHE_BAS_DROITE_GAUCHE_BAS_GAUCHE_DROITE_DROITE_GAUCHE_GAUCHE_GAUCHE_BAS_BAS_BAS_BAS_GAUCHE_GAUCHE_BAS_GAUCHE_DROITE_BAS_GAUCHE_GAUCHE_GAUCHE_GAUCHE_BAS_GAUCHE_DROITE_BAS_GAUCHE_GAUCHE_GAUCHE_GAUCHE_BAS_DROITE_GAUCHE_DROITE_BAS_BAS_GAUCHE_GAUCHE_GAUCHE_BAS_GAUCHE_DROITE_GAUCHE_BAS_DROITE_BAS_DROITE_DROITE_BAS_DROITE_DROITE_BAS_DROITE_GAUCHE_BAS_GAUCHE_GAUCHE_GAUCHE_GAUCHE_GAUCHE_GAUCHE_GAUCHE_DROITE_DROITE_GAUCHE_BAS_BAS_GAUCHE_BAS_GAUCHE_GAUCHE_HAUT_DROITE_GAUCHE_HAUT_DROITE_HAUT_HAUT_HAUT_HAUT_HAUT_HAUT_HAUT_DROITE_GAUCHE_DROITE_DROITE_HAUT_DROITE_HAUT_GAUCHE_GAUCHE_DROITE_GAUCHE_HAUT_GAUCHE_HAUT_HAUT_HAUT_HAUT_HAUT_GAUCHE_GAUCHE_HAUT_HAUT_HAUT_HAUT_HAUT_GAUCHE_HAUT_DROITE_DROITE_HAUT_GAUCHE_DROITE_DROITE_HAUT_DROITE_HAUT_HAUT_GAUCHE_HAUT_HAUT_HAUT_HAUT_GAUCHE_DROITE_HAUT_HAUT_HAUT_GAUCHE_HAUT_HAUT_GAUCHE_HAUT_HAUT_GAUCHE_GAUCHE_HAUT_HAUT_HAUT_HAUT_GAUCHE_GAUCHE_HAUT_HAUT_GAUCHE_HAUT_HAUT_GAUCHE_DROITE_GAUCHE_HAUT_HAUT_GAUCHE_HAUT_DROITE_GAUCHE_HAUT_HAUT_GAUCHE_GAUCHE_GAUCHE_GAUCHE_HAUT_DROITE_GAUCHE_GAUCHE_DROITE_HAUT_HAUT_DROITE_GAUCHE_HAUT_BAS_HAUT_HAUT_BAS_GAUCHE_HAUT_HAUT_BAS_GAUCHE_HAUT_BAS_BAS_GAUCHE_HAUT_HAUT_BAS_BAS_BAS_DROITE_GAUCHE_BAS_BAS_HAUT_GAUCHE_HAUT_DROITE_GAUCHE_DROITE_BAS_GAUCHE_BAS_HAUT_BAS_GAUCHE_GAUCHE_GAUCHE_BAS_DROITE_HAUT_BAS_GAUCHE_GAUCHE_DROITE_BAS_GAUCHE_GAUCHE_BAS_BAS_HAUT_GAUCHE_DROITE_HAUT_BAS_HAUT_DROITE_GAUCHE_DROITE_GAUCHE_BAS_BAS_HAUT_BAS_HAUT_BAS_HAUT_HAUT_DROITE_BAS_HAUT_BAS_BAS_GAUCHE_GAUCHE_HAUT_GAUCHE_BAS_DROITE_BAS_BAS_GAUCHE_BAS_GAUCHE_HAUT_HAUT_HAUT_HAUT_BAS_GAUCHE_HAUT_HAUT_BAS_GAUCHE_HAUT_GAUCHE_BAS_BAS_DROITE_HAUT_DROITE_HAUT_BAS_GAUCHE_DROITE_BAS_BAS_BAS_GAUCHE_DROITE_GAUCHE_DROITE_DROITE_BAS_GAUCHE_GAUCHE_HAUT_GAUCHE_HAUT_DROITE_GAUCHE_BAS_HAUT_BAS_BAS_GAUCHE_HAUT_DROITE_DROITE_GAUCHE_HAUT_DROITE_HAUT_GAUCHE_DROITE_HAUT_DROITE_HAUT_GAUCHE_GAUCHE_BAS_BAS_BAS_GAUCHE_GAUCHE_DROITE_GAUCHE_BAS_DROITE_BAS_GAUCHE_DROITE_GAUCHE_GAUCHE_GAUCHE_HAUT_BAS_BAS_DROITE_DROITE_HAUT_BAS_DROITE_DROITE_HAUT_BAS_BAS_DROITE_GAUCHE_HAUT_DROITE_GAUCHE_HAUT_DROITE_BAS_DROITE_DROITE_BAS_DROITE_DROITE_HAUT_HAUT_BAS_HAUT_BAS_GAUCHE_DROITE_HAUT_GAUCHE_BAS_BAS_DROITE_DROITE_BAS_DROITE_HAUT_GAUCHE_DROITE_DROITE_HAUT_DROITE_HAUT_GAUCHE_BAS_DROITE_DROITE_BAS_HAUT_BAS_BAS_HAUT_DROITE_HAUT_HAUT_BAS_GAUCHE_BAS_HAUT_HAUT_DROITE_GAUCHE_GAUCHE_DROITE_DROITE_HAUT";
	int count = strlen(map);
	int count2 = strlen(map2);

	printf("Carte:\n");

	for (int i1 = 0; i1 < count; i1 = i1 + 1)
	{
		if (map[i1] == '<')
		{
			start = start - 1;
		}
		else
		{
			start = start + 1;
		}
	}
	x = start;
	printf("La case d'arrivé est: %d\n", start);

	while(i < count2)
	{

		if (map2[i] == 'G')
		{
			x = x - 1;
			i = i + 7;
		}
		else if (map2[i] == 'D')
		{
			x = x + 1;
			i = i + 7;
		}
		else if (map2[i] == 'H')
		{
			y = y + 1;
			i = i + 5;
		}
		else if (map2[i] == 'B')
		{
			if (y != -2)
			{
				y = y - 1;
				
			}
			i = i + 4;
			
		}
		else
		{
			printf("Erreur Pas H, G, D ou B\n");
			break;
		}
	}
	printf("Les coordonées sont: %d,%d\n", x, y);
	exit(0);

}